// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtcfhgOm43Cv_8PWfCkEw2btCiA6wuF2Y',
    appId: '1:269393820854:web:02c5f9205c8e148fb83a17',
    messagingSenderId: '269393820854',
    projectId: 'attendence-e606e',
    authDomain: 'attendence-e606e.firebaseapp.com',
    storageBucket: 'attendence-e606e.appspot.com',
    measurementId: 'G-GTE4H45ZEC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCczRaWBFyTa4EPBsqU7PG_K5DuBOFFkfg',
    appId: '1:269393820854:android:7e6e496dcf7bf856b83a17',
    messagingSenderId: '269393820854',
    projectId: 'attendence-e606e',
    storageBucket: 'attendence-e606e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVmEUBv5h7ok-FOVGQb1-4equAESZ96Vs',
    appId: '1:269393820854:ios:e6d1084a36ad62c9b83a17',
    messagingSenderId: '269393820854',
    projectId: 'attendence-e606e',
    storageBucket: 'attendence-e606e.appspot.com',
    iosBundleId: 'com.example.attendence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVmEUBv5h7ok-FOVGQb1-4equAESZ96Vs',
    appId: '1:269393820854:ios:6bf0814ea2839955b83a17',
    messagingSenderId: '269393820854',
    projectId: 'attendence-e606e',
    storageBucket: 'attendence-e606e.appspot.com',
    iosBundleId: 'com.example.attendence.RunnerTests',
  );
}
